repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.4.0
        hooks:
            -   id: check-yaml
            -   id: check-json
            -   id: check-toml
            -   id: check-xml
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.0.291
        hooks:
            -   id: ruff
                args: [--fix, --exit-non-zero-on-fix]
    -   repo: https://github.com/psf/black-pre-commit-mirror
        rev: 23.9.1
        hooks:
            -   id: black
default_language_version:
    python: python3.11
